package ccboybot

const (
	ROUTE_PATH = "/ccboy"
)

const (
	ENV_BOT_CHANNEL_SECRET       = "BOT_CHANNEL_SECRET"
	ENV_BOT_CHANNEL_ACCESS_TOKEN = "BOT_CHANNEL_ACCESS_TOKEN"
	ENV_BOT_USER_ID              = "BOT_CHANNEL_USER_ID"
)

const (
	MENU_LION       = "/雄獅"
	MENU_LION_TO_UX = "/toUX"
	MENU_LION_TO_IT = "/toIT"
)

const (
	STATE_NONE = iota
	STATE_LINE_PENDING_FOR_CHOOSE
	STATE_LION_PENDING_FOR_TO_UX_RANGE
	STATE_LION_PENDING_FOR_TO_UX_URL
	STATE_LION_PENDING_FOR_TO_IT_RANGE
	STATE_LION_PENDING_FOR_TO_IT_CONTENT
	STATE_LION_PENDING_FOR_TO_IT_URL
)
